# Generated by Django 4.2.3 on 2024-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('CLIENTE', 'cliente'), ('REPARTIDOR', 'repartidor')], default='cliente', max_length=10),
        ),
    ]
