# Generated by Django 4.2.3 on 2024-09-24 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('owner_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enterprise_owner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=255)),
                ('avatar', models.ImageField(default='avatar.png', upload_to='')),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='enterprise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_enterprise', to='users.enterprise'),
        ),
    ]
