# Generated by Django 4.2.3 on 2024-08-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='can_publish',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
