# Generated by Django 4.2.3 on 2025-04-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mercadopagoconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercadopagoconfig',
            name='refresh_token',
        ),
    ]
