# Generated by Django 4.2.3 on 2024-08-30 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_last_name_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='date_requested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_publish',
            field=models.CharField(choices=[('vendiendo', 'vendiendo'), ('solicitando', 'solicitando'), ('cliente', 'cliente')], default='cliente', max_length=20),
        ),
    ]
