# Generated by Django 4.2.3 on 2024-09-24 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_enterprise_user_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_reviews', to=settings.AUTH_USER_MODEL)),
                ('user_wrote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
