# Generated by Django 4.2.3 on 2024-08-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_staff_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('CLIENT', 'client'), ('SELLER', 'seller')], default='client', max_length=10),
        ),
    ]
