# Generated by Django 4.2.3 on 2024-09-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
