# Generated by Django 4.2.3 on 2024-08-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_publish',
            field=models.BooleanField(default=False),
        ),
    ]
