# Generated by Django 4.2.3 on 2024-09-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
