# Generated by Django 4.2.3 on 2024-09-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_num_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_politicy',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
