# Generated by Django 4.2.3 on 2024-09-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_accepted_politicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='link_enterprise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
