# Generated by Django 4.2.3 on 2024-09-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_enterprise_link_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='rut',
            field=models.TextField(default='img in base 64', help_text='Imagen del RUT en formato base64'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='tipo_productos',
            field=models.CharField(default='Varios', help_text='Lista de tipos de productos separados por comas', max_length=255),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='avatar',
            field=models.TextField(default='img in base 64', help_text='Imagen del avatar en formato base64'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='link_enterprise',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='img in base 64', help_text='Imagen del avatar en formato base64'),
        ),
    ]
