# Generated by Django 4.2.3 on 2024-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_enterprise_facebook_enterprise_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='description',
            field=models.CharField(default='Description in blank', max_length=255),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='products_length',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
