# Generated by Django 4.2.3 on 2024-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_enterprise_description_enterprise_products_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='link_enterprise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
