version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NcwYPXheNEwafmCNadOBVebiOOxnrHOs
    ports:
      - "42749:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: railway
      DB_USER: postgres
      DB_PASSWORD: NcwYPXheNEwafmCNadOBVebiOOxnrHOs
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py createsuperuser --noinput || true && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      VITE_BACKEND_URL: http://localhost:8000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  pgdata:
