# Generated by Django 4.2.3 on 2024-09-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='ShoppingAddress',
        ),
    ]
