<<<<<<< HEAD
# Generated by Django 4.2.3 on 2024-09-09 21:36
=======
# Generated by Django 4.2.3 on 2024-09-09 20:49
>>>>>>> a2d275528d27c4f6da782963950f9bfabb4b5810

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
=======
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
>>>>>>> a2d275528d27c4f6da782963950f9bfabb4b5810
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
