# Generated by Django 4.2.3 on 2025-10-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryorder',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='temporaryorder',
            name='provider',
            field=models.CharField(default='mercadopago', max_length=50),
        ),
    ]
