# Generated by Django 4.2.3 on 2025-03-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_is_paid_order_paid_at_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
