# Generated by Django 4.2.3 on 2025-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_shoppingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
