# Generated by Django 4.2.3 on 2025-04-01 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_order_seller_order_shipping_price_order_tax_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='seller_id',
        ),
        migrations.AlterField(
            model_name='temporaryorder',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_temp_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
