# Generated by Django 4.2.3 on 2025-04-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderitem_seller_id_and_more'),
    ]

    operations = [
    ]
