# Generated by Django 4.2.3 on 2024-09-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('FRUTAS', 'Frutas'), ('VERDURAS', 'Verduras'), ('GRANOS', 'Granos'), ('ABARROTES', 'Abarrotes'), ('UNIDAD', 'Unidad'), ('OTROS', 'Otros')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=350)),
                ('map_locate', models.CharField(default='desconocido', max_length=100)),
                ('locate', models.CharField(default='desconocido', max_length=100)),
                ('count_in_stock', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('num_reviews', models.IntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tiempoL', models.IntegerField(default=0)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='placeholder.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
