# Generated by Django 4.2.3 on 2024-08-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='locate',
            field=models.CharField(default='desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='map_locate',
            field=models.CharField(default='desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
