# Generated by Django 4.2.3 on 2024-09-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_in_sells',
            field=models.IntegerField(default=0),
        ),
    ]
