# Generated by Django 4.2.3 on 2024-08-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_slug_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='slug',
        ),
    ]
