# Generated by Django 4.2.3 on 2024-08-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='description',
            new_name='comment',
        ),
    ]
