# Generated by Django 4.2.3 on 2024-08-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_description_reviews_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
    ]
