# Generated by Django 4.2.3 on 2024-08-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_product_id_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FRUTAS', 'Frutas'), ('VERDURAS', 'Verduras'), ('GRANOS', 'Granos'), ('ABARROTES', 'Abarrotes'), ('OTROS', 'Otros')], max_length=100),
        ),
    ]
